### ISSUE TITLE
Taktikák

### ISSUE THREAD

**Issue by AstroTsiga** [LactatingCorgi/MAF_hearts#1]

**Comment by AstroTsiga** [comment]
A twentysix-hez lehetne, hogy figyeli, hogy elvihető-e még mind a 26 pont, mert ha nem, ergo ha valamelyik másik játékos szerzett pontot, akkor átválthatna valmelyik másik stratégiára.

Ha passzolás után maradnak kis lapok, olyan színből, amiből kevés van, akkor az elején meg lehetne próbálni egy-két olyat eldoni, mert ha azok a kör végére maradnak meg, akkor nem lehet dekket vinni.

Ha esetleg egy színből nagyon sok van, akkor lehetne azt hagyni a végére; úgy is el lehet vinna az összes lapot, ha folyton olyan színt dobsz, amiből már egyik játékosnak sincs.

**Comment by AstroTsiga** [comment]
Pontszerzést kerülő stratégiákhoz: Ha osztásnál nem hozzá került a pikk dáma, akkor érdemes nem elpasszolni a pikkeket, akkor sem, ha kevés van belőle, mert ha aztán átadásnál megkapja, akkor nehéz lesz elkerülni, hogy ne kelljen lerakni, és azzal elvinni.
Ha aztán nem kapja meg valakitől a pikk dámát, akkor is jó, ha sok pikkje van, mert azokat tudja rakosgatni, a legnagyobbakkal kezdve, hogy esetleg a következő körben is ő nyithasson, és kicsikarhassa a pikk dámát.

**Comment by AstroTsiga** [comment]
A less colors nyilván nem mindig olyan színt tesz, amiből a legkevesebb van, hanem amikor olyan színnel nyitnak, amije nincs, akkor minél erősebb, pontot érő lapot rak.

A pikk Király, pikk Ász ugyan úgy kerülendő lapok, mint a kőrök, szóval a mohó belekalkulálhatná azokat is, mintha azok pl 14 és 15 pontot érnének.

Az első körben ugyebár nem szabad pontot érő lapot dobni, kivéve ha csak kőröd vagy pikk dámád van, aminek az esélye kb 0, ezért az első körben nyugodtan lehet minél magasabb treffet dobni, mert a kezdés némi előnnyel jár. Pl ha én kezdek, akkor dámánál gyengébb pikk lapot dobok (esetleg ezekből is a legnagyobbat), hogy minél korábban kikényszerítsem, hogy eldobják a pikk dámát, és valaki más vigye el.
Ilyen szempontból a treff 2-est is érdemes átadni.

**Comment by LactatingCorgi** [comment]
> A twentysix-hez lehetne, hogy figyeli, hogy elvihető-e még mind a 26 pont, mert ha nem, ergo ha valamelyik másik játékos szerzett pontot, akkor átválthatna valmelyik másik stratégiára.

> Ha passzolás után maradnak kis lapok, olyan színből, amiből kevés van, akkor az elején meg lehetne próbálni egy-két olyat eldoni, mert ha azok a kör végére maradnak meg, akkor nem lehet dekket vinni.

> Ha esetleg egy színből nagyon sok van, akkor lehetne azt hagyni a végére; úgy is el lehet vinna az összes lapot, ha folyton olyan színt dobsz, amiből már egyik játékosnak sincs.

A színűrítés az egy kicsit hajazna a less colorsra, de végülis beleprogramozható - csak kérdés, hogy mikor és miért döntsön így? 

A twentysix célja az, hogy mindenképp vigye a pontot érő lapokat. Ezért kis lapokat nem fog bedobni mindaddig, amíg nem érzi úgy, hogy azokkal a lapokkal már nem fog találkozni. Erre megoldás lehet az, hogy figyeli, milyen lapok kerültek már játékba, és ha egy adott szint alatt van az ilyen lapok száma, akkor dobja be...már ha ő kezd. Én inkább azt mondanám, hogy a kis lapokat akkor dobja be, ha nincs (még) tétje a dekknek. Inkább azt vigyék mások, amiben nincs semmi.

A stratégiaváltással viszont nem értek egyet. A twentysixnek pont az a célja, hogy high risk, high reward elven megpróbáljon valaki mást felvinni 100 pontra azelőtt, hogy ő menne fel 100 pontra.

**Comment by LactatingCorgi** [comment]
> Pontszerzést kerülő stratégiákhoz: Ha osztásnál nem hozzá került a pikk dáma, akkor érdemes nem elpasszolni a pikkeket, akkor sem, ha kevés van belőle, mert ha aztán átadásnál megkapja, akkor nehéz lesz elkerülni, hogy ne kelljen lerakni, és azzal elvinni. Ha aztán nem kapja meg valakitől a pikk dámát, akkor is jó, ha sok pikkje van, mert azokat tudja rakosgatni, a legnagyobbakkal kezdve, hogy esetleg a következő körben is ő nyithasson, és kicsikarhassa a pikk dámát.

Ezt hogy akarjuk beilleszteni a pár szabályt követő stratégiákba? Mert ez megnyitná Pandora szelencséjét, hogy "ha ilyen a leosztás, akkor ez, ha olyan, akkor az". Én is örülnék, ha lenne időnk egy neurális hálót tanítani pártízezer játékkal, de nincs.

**Comment by LactatingCorgi** [comment]
> A less colors nyilván nem mindig olyan színt tesz, amiből a legkevesebb van, hanem amikor olyan színnel nyitnak, amije nincs, akkor minél erősebb, pontot érő lapot rak.
> 
> A pikk Király, pikk Ász ugyan úgy kerülendő lapok, mint a kőrök, szóval a mohó belekalkulálhatná azokat is, mintha azok pl 14 és 15 pontot érnének.
> 
> Az első körben ugyebár nem szabad pontot érő lapot dobni, kivéve ha csak kőröd vagy pikk dámád van, aminek az esélye kb 0, ezért az első körben nyugodtan lehet minél magasabb treffet dobni, mert a kezdés némi előnnyel jár. Pl ha én kezdek, akkor dámánál gyengébb pikk lapot dobok (esetleg ezekből is a legnagyobbat), hogy minél korábban kikényszerítsem, hogy eldobják a pikk dámát, és valaki más vigye el. Ilyen szempontból a treff 2-est is érdemes átadni.

Mohó kalkuláció nekem oké, az logikusnak tűnik. A less colorsnál én arra gondoltam, hogy úgy írt színeket, hogy minél kevesebb legyen nála, és nem részesíti előnyben a pontot érő lapokat. Neki az mindegy, mit dob, úgyse ő fogja vinni a kör felétől, hiszen nagy eséllyel olyan színt rak, amivel nem ő nyitott. Ha ő a kezdő, akkor lehet kicsitől kezdve dobnia a lapokat, és óvatosan bánnia a pontot érőkkel.

**Comment by AstroTsiga** [comment]
Rendben, ezek így jók.
Természetesen, ha már az megvan, ami a pdf-ben van, bőven jók vagyunk, nem akartam nagyon elrugaszkodni ^^;
